service: fiap-lab

frameworkVersion: '3'

plugins:
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: files-${self:custom.stage}
  bucket: br-com-fiap-files-${self:custom.stage}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

functions:
  files:
    handler: index.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: entrada-dados/
            - suffix: .json
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: entrada-dados/
            - suffix: .json
